import ClientProvider from '@/components/ClientProvider';
import Login from '@/components/Login';
import Sidebar from '@/components/Sidebar'
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import { getServerSession } from 'next-auth';
import { SessionProvider } from '../components/SessionProvider'
import '../styles/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const session = await getServerSession(authOptions)
  
  return (
    <html lang="en">
      <head />
      <body>
      <SessionProvider session={session}>
        {!session ? (
          <Login />
        ): (
        <div className='flex'>
          {/* Sidebar */}
          <div className="bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem]">
            <Sidebar />
          </div>

          <ClientProvider />

          {/* client provider - notification */}
        <div className="bg-[#343541] flex-1">{children}</div>
        </div>
        
        )}
        </SessionProvider>
      </body>
    </html>
  )
}
